Use Python 3.9 in Travis builds (#1783)
* Use Python 3.9 in Travis builds

* Remove `--user` because pip works in a virtualenv

  Fixes the following error:
  ```
  ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
  ```