ci: use bobheadxi/deployments@v1.3.0
Since bobheadxi/deployments@v1.4.0 we had a CI failure with the
following error in `destroy-deployments` and
`destroy-deployments-manually`, step `remove-github-deployment`:
```
unexpected error encountered: HttpError: Resource not accessible by integration
Error: unexpected error encountered: HttpError: Resource not accessible by integration - see logs for more information
```

This patch returns version 1.3.0 that worked OK.

Part of #3390