ci: use bobheadxi/deployments@v1.3.0 (#3393)
This patch fixes retry_wait_seconds for nick-field/retry action
so the command has enough time for correct executing. Before this patch,
we had this step always failing with the real webhook task finished
successfully.

Part of https://github.com/tarantool/doc/issues/3390

_______

Since bobheadxi/deployments@v1.4.0 we had a CI failure with the 
following error in `destroy-deployments` and  
`destroy-deployments-manually`, step `remove-github-deployment`:                                                                                                        
```                                                                                                                     
unexpected error encountered: HttpError: Resource not accessible by integration                                         
Error: unexpected error encountered: HttpError: Resource not accessible by integration - see logs for more information  
```                                                                                                                     
                                                                                                                        
This patch returns version 1.3.0 that worked OK.                                                                        
                                                                                                                        
Part of #3390
______

Closes #3390