Remove --user because pip works in a virtualenv
Fixes the following error:
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.